### ISSUE TITLE
Parse error (MacOS)

### ISSUE THREAD

**Issue by toringe** [rhyeal/aws-rotate-iam-keys#10]
Fresh install from homebrew (rhyeal/aws-rotate-iam-keys/aws-rotate-iam-keys: stable 0.9.0) gives me this runtime error:
```
$ aws-rotate-iam-keys
Making new access key
parse error: Invalid numeric literal at line 1, column 10
```
When checking in IAM, I can see that the script has created a new secondary access key, but has not updated my credentials file, nor removed the old primary key.

**Comment by mmrwoods** [comment]
@toringe Looks like a failure to parse the response from the AWS CLI using jq on line 85:

```
...
RESPONSE=$(aws iam create-access-key --profile $FIRST_PROFILE | jq .AccessKey)
...
```

Which version of jq are you running? `jq --version`

If you delete the new access key that was created by the script and then manually run the AWS CLI command to create a new access key, e.g. `aws iam create-access-key --profile default`, does the response look something like this...

```
{
    "AccessKey": {
        "UserName": "your-user-name",
        "AccessKeyId": "XXXXXXXXXXXXXX",
        "Status": "Active",
        "SecretAccessKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "CreateDate": "2019-02-27T07:44:20Z"
    }
}
```

**Comment by toringe** [comment]
Hi @mmrwoods. My `jq` is version 1.6. And I do get the output, but my config defaults to text output.  Does the `aws-rotate-iam-keys` script assume json output, or does it explicitly set `--output json`? Because if it doesn't, that is why jq is complaining I guess.

**Comment by mmrwoods** [comment]
HI @toringe,

seems you have uncovered a bug, that particular invocation of the aws cli on line 85 is missing the `--output json` option.

Does it work if you edit `/usr/local/bin/aws-rotate-iam-keys` and change line 85 to:

```  
RESPONSE=$(aws iam create-access-key --output json --profile $FIRST_PROFILE | jq .AccessKey)
```

**Comment by sydney-sisco** [comment]
I had the same issue as @toringe. Editing line 85 as you described has resolved the issue. 👍

**Comment by toringe** [comment]
Yes, as @sydney-sisco already confirmed, adding `--output json` to line 85 does the trick.
