### ISSUE TITLE
Xenial is not supported from the rhyeal ppa - only Bionic

### ISSUE THREAD

**Issue by eburcat** [rhyeal/aws-rotate-iam-keys#13]

**Comment by rhyeal** [comment]
End of standard support for 16.04 is 2021. I don't have a 16.04 LTS machine outside of a VM, so I can look into adding 16.04 support, but I wouldn't expect that this is a high priority for me right now.

**Comment by rhyeal** [comment]
I will be releasing the same binaries for Eoan, Xenial and Bionic now through PPA.
