### ISSUE TITLE
When the Windows folder name contains spaces - the execution of the task fails - missing escaping of whitespace in $folder

### ISSUE THREAD

**Issue by eburcat** [rhyeal/aws-rotate-iam-keys#15]

**Comment by rhyeal** [comment]
I'll have to look into this. Seems like reproducing it is simply adding a space to the folder name, correct?

**Comment by MarcSamD** [comment]
@rhyeal Yes, easy to reproduce and easy to fix as it only needs to add -File before the path, refer to the commit 468f60f
