### ISSUE TITLE
Error when running the script in MacOS environment

### ISSUE THREAD

**Issue by mmota-pipefy** [rhyeal/aws-rotate-iam-keys#2]
Greetings,

I'm receiving this error when trying to run the script in a MacOS environment (Mojave).

This is the error i'm receiving:

`I'm sorry, -- failed in this environment.`

Any idea what it could be? Just to let you know, this is a complete from scratch MacOS installation. All that was installed was from the brew installation only (awscli, jq, etc.)

Thanks in advance!

**Comment by ntkach** [comment]
FWIW I was able to resolve this by making sure that gnu-getopt was in my PATH before Apple's quirky one
`brew install gnu-getopt`
`echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile`
then of course you have to either log out and back in or run the export part manually the first time.

**Comment by Jolg42** [comment]
Same issue for me on macOS High Sierra (10.13.6)

`gnu-getopt` was installed but adding it to the `PATH` was required to make it work, thanks @ntkach !

**Comment by zar777** [comment]
Hi,

@ntkach , @Jolg42 have you tried to run the script with the crontab? If I run the script manually if works without any issue but if I schedule to run the script via the crontab, I have the same error --> 
**I’m sorry,  -- failed in this environment.**

Below the crontab snippet:

```
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/opt/gnu-getopt/bin:$PATH
* * * * * /bin/bash /usr/local/Cellar/aws-rotate-iam-keys/0.8.1/bin/aws-rotate-iam-keys --profile prd >/tmp/log.txt 2>&1
```

**Comment by Jolg42** [comment]
I only tried from the command line and it didn't work, PR #3 looks good, didn't try it yet though.

**Comment by zar777** [comment]
@Jolg42 in the first comment you said that the workaround fixed the issue but now you're saying it doesn't work. Am I missing something? In addition, can you please let me know if the script executed via the crontab works for you?

Thanks

**Comment by Jolg42** [comment]
@zar777 Indeed it did work after the workaround ;-)
And after testing it, it also works in my crontab.

_By the way if you want to use the default profile for Elastic Beanstalk here is a trick https://stackoverflow.com/questions/29190202/how-to-change-the-aws-account-using-the-elastic-beanstalk-cli/54077249#54077249_

**Comment by zar777** [comment]
@Jolg42 Thanks for your quick reply.

It's not a problem for me to run the script in my crontab using the workaround, I'm interested to make it works for now :D . Can you please paste here what you have in your crontab file? It can be helpful.
Thanks.

**Comment by Jolg42** [comment]
@zar777 Just `* */6 * * * aws-rotate-iam-keys` (Every 6 hours)

And in my ~/.zshrc `export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"`
