### ISSUE TITLE
Error: ChecksumMismatchError: SHA256 mismatch during brew install

### ISSUE THREAD

**Issue by jasoniangreen** [rhyeal/aws-rotate-iam-keys#29]
I think you updated the sha256 in `Formula/aws-rotate-iam-keys.rb` but forgot to also update the url to `0.9.5`. I am getting a SHA256 mismatch error when installing with brew.

**Comment by danielmunro** [comment]
running into this as well, thank you @jasoniangreen for documenting and proposing a PR fix! Also thank you @rhyeal for this excellent tool.

**Comment by NaitoKenzo** [comment]
Hi there, is there anything I can do to help this move forward? I'd love to make my team use this. Cheers!

**Comment by jasoniangreen** [comment]
@rhyeal did you go on holiday?

**Comment by avivezer-salesforce** [comment]
I have the same issue...

**Comment by mmrwoods** [comment]
@jasoniangreen @danielmunro @NaitoKenzo @avivezer-salesforce While waiting for a new stable release with a valid checksum, you can install the latest HEAD version using `brew install aws-rotate-iam-keys --HEAD`. This will install from the head commit on master, without verifying a checksum.

**Comment by rhyeal** [comment]
re-opening this to remind myself to work on the CI/CD pipeline for this tomorrow

**Comment by rhyeal** [comment]
The CI/CD pipeline should be pushing out a correct SHA256 hash now automatically for MacOS // homebrew. I have another bug to squash with the version number, but this issue should be fixed for good now!
