### ISSUE TITLE
Latest release differs greatly from master branch

### ISSUE THREAD

**Issue by albertocastro63** [rhyeal/aws-rotate-iam-keys#34]
The master branch currently has a script that performs a verification of the validity of the newly generated AWS IAM Keys. That verification is missing from the latest release `v0.9.2`. Furthermore the master branch is 42 commits ahead of the latest release. Are there any plans to create a new release soon?

**Comment by albertocastro63** [comment]
It seems that a new release was posted with the new changes. Thank you! Closing the issue,

**Comment by rhyeal** [comment]
Glad this worked for you! I'm spending a portion of the day today to get this tool cleaned up and add some tests to prevent this issue from happening again.
