### ISSUE TITLE
CircleCI job to update homebrew hashes wipes out other changes?

### ISSUE THREAD

**Issue by mmrwoods** [rhyeal/aws-rotate-iam-keys#38]
Hi @rhyeal,

I merged the PR to fix the invalid Homebrew devel spec this morning, but the change added by the PR was wiped out by a commit added via the `homebrew` CircleCI job.

See the latest commit to master, cfe2b1e76f376b19147ef1c8b5d24436a330a3fa.

I think the problem might be the `restore_cache` configuration, which looks like it will restore a cache matching `v1-repo-{{ .Branch }}` when one matching `v1-repo-{{ .Branch }}-{{ .Revision }}` is missing.

**Comment by rhyeal** [comment]
Ugh, yeah I see that. I'm booked tomorrow, but I'll try to find some time on Friday this week to fix that CI/CD script. I also want to get the version to automatically update so it doesn't error when uploading to Launchpad like what happened with the first merge earlier tonight.

**Comment by rhyeal** [comment]
Took a look at the commit and realized what was happening. https://github.com/rhyeal/aws-rotate-iam-keys/pull/39 should fix it

**Comment by mmrwoods** [comment]
Closing, this is a general issue re use of templates to generate code, which requires updating the templates when making changes, rather than the source that is used by say the Homebrew formula.

See discussion on issue #39 which explains the problem in more detail
