### ISSUE TITLE
Error when running the script via the Crontab on Macos

### ISSUE THREAD

**Issue by zar777** [rhyeal/aws-rotate-iam-keys#4]
Hi, 

I'm having several issues when I'm trying to set up a crontab as the README suggests. The job runs and it gives me the following error: 

> cron[65841]: no path for address 0x1115fa000

I google the error and I tried to add also the path of the script on the top of the file. FYI, I'm using zsh as shell.

Here an example of what I have in the crontab:

![screen shot 2019-01-04 at 16 56 41pm](https://user-images.githubusercontent.com/2695741/50700205-de4cbb00-1041-11e9-8254-19921177c0af.png)

Thanks in advance.

**Comment by rhyeal** [comment]
@zar777 We recently released v0.9.0 of this with updated homebrew support for MacOS. Are you still having this issue?

**Comment by rhyeal** [comment]
Closing this issue out as additional support has been provided with a homebrew update two releases ago. If this is still an issue, please feel free to re-open this issue.
