### ISSUE TITLE
/bin/sh: aws-rotate-iam-keys: command not found

### ISSUE THREAD

**Issue by changhyuni** [rhyeal/aws-rotate-iam-keys#58]
My Crontab is :
 "* * * * * aws-rotate-iam-keys --profile dev >> ~/Desktop/naver_blog_cron.log 2>&1"
 
 log is /bin/sh: aws-rotate-iam-keys: command not found
 Is there anything I'm missing?
 
 thx!

**Comment by cowdude** [comment]
You likely need to specify the absolute path where you installed `aws-rotate-iam-keys`. Relative paths *usually* don't work with cron daemons.
