### ISSUE TITLE
support rotating govcloud keys

### ISSUE THREAD

**Issue by fawaf** [rhyeal/aws-rotate-iam-keys#65]
```
waf % aws-rotate-iam-keys --profile govcloud
Rotating keys for profiles: govcloud
Verifying configuration
Verifying credentials

An error occurred (InvalidClientTokenId) when calling the ListAccessKeys operation: The security token included in the request is invalid.
waf %
```

**Comment by mmrwoods** [comment]
@fawaf Sorry about the long, long delay following up on this. This looks like a permissions issue and not specifically related to govcloud. I can't find any documentation that suggest rotating keys on govcloud is any different to standard aws accounts, and I don't have a govcloud account so I can't reproduce.

Please re-open it this remains an issue, add any additional information you have that might aid investigation.
