### ISSUE TITLE
Error scheduling with brew service

### ISSUE THREAD

**Issue by JamesG419** [rhyeal/aws-rotate-iam-keys#66]
My computer
`sw_vers
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165`

My version of homebrew
`brew --version
Homebrew 3.2.16
Homebrew/homebrew-core (git revision d1b07a4bbb0; last commit 2021-10-13)
Homebrew/homebrew-cask (git revision 467a76e4da; last commit 2021-10-14)`

I can run the command `aws-rotate-iam-keys --profiles default,{profile}` and successfully rotate my keys. I've tried starting the brew service, added `--profiles default,{profile}` as the only line in my /usr/local/etc/aws-rotate-iam-keys, and then restarted.

Brew is reporting an error with the service and when I check the logs I see: 
`Rotating keys for profiles: default,{profile}
Verifying configuration
Could not find keys for profile default. Ensure you have a profile set up using 'aws configure'.`

Has anyone seen this before?

**Comment by mmrwoods** [comment]
Hi, sorry about the delay following up on this.

When you run `aws-rotate-iam-keys --profiles default,{profile}` it's trying to rotate one set of keys referenced by two profiles, one named "default" and the other named "{profile}". 

Do you really have these two AWS configuration profiles? Though "{profile}" may well be valid profile name, it's also a shell glob pattern so it's possible that the source of the problem.

You can see all of the commands being run by `aws-rotate-iam-keys` if you (temporarily) edit `/usr/local/bin/aws-rotate-iam-keys` and add `set -x` as the second line. Then run `brew services restart aws-rotate-iam-keys` and check the log file at `/tmp/homebrew.mxcl.aws-rotate-iam-keys.log`. You should be able to see commands being run to verify the profiles, and try running the commands manually to see which one is failing.

**Comment by JamesG419** [comment]
Hi, 
The other profile name is something else. Probably could have said `--profiles default,foo` I'll follow up on the `set -x` suggestion. Thank you!

**Comment by mmrwoods** [comment]
Closing as access key rotation script now logs more info when profile verification fails for some reason, which should be enough to help users identify the problem with their configuration and solve it themselves.
