### ISSUE TITLE
Windows setup help.. 

### ISSUE THREAD

**Issue by markdavidburke** [rhyeal/aws-rotate-iam-keys#68]
Hello - sorry if this is a silly question, I've set this up on linux a lot of times and setting the azure_tenant_id and  azure_app_id_uri is pretty simple but I'm stuck with windows. 

I've ran the powershell script but don't understand how to set up the config, can anyone help a simpleton? 

`Could not load profile. Please set up AWS PowerShell Tools first before running this command!`

**Comment by gonzalez** [comment]
@markdavidburke  have you tried installing the tools ?  https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-windows.html
