### ISSUE TITLE
Warning: Calling plist_options is deprecated! Use service.require_root instead

### ISSUE THREAD

**Issue by ghost** [rhyeal/aws-rotate-iam-keys#74]
Seeing this warning for `brew outdated`.  It probably appears for other brew commands but this is where I'm seeing it often.

> Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the rhyeal/aws-rotate-iam-keys tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/rhyeal/homebrew-aws-rotate-iam-keys/Formula/aws-rotate-iam-keys.rb:53

**Comment by sirantd** [comment]
Created PR #75

**Comment by jumarko** [comment]
I'm also seeing this warning - @rhyeal would you mind looking at the PR that @sirantd created?

**Comment by kodcuserkan** [comment]
I'm also seeing this warning help please!

**Comment by kodcuserkan** [comment]
> Created PR #75

Any update? Thanks in advance!
